version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    groups:
      nextjs:
        patterns:
          - "next"
          - "react"
          - "react-dom"
      firebase:
        patterns:
          - "firebase*"
          - "@firebase/*"
      testing:
        patterns:
          - "@testing-library/*"
          - "jest*"
          - "@types/jest"
          - "@playwright/*"
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
