steps:
  - id: build-backend-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=backend/Dockerfile
      - --tag=gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA
      - .
    # Use the repository root as the build context so the workspace manifests
    # (pnpm-lock.yaml, pnpm-workspace.yaml, package.json) are available to COPY
    # directives inside backend/Dockerfile.
    dir: .
images:
  - gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA
