steps:
  - id: build-backend-image
    name: gcr.io/cloud-builders/docker
    # Run from the repo root so the Docker build context includes the workspace manifests
    dir: .
    # The final '.' sets the Docker context to the repo root so pnpm-lock.yaml and pnpm-workspace.yaml are available
    args:
      - build
      - --file=backend/Dockerfile
      - --tag=gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA
      - .
images:
  - gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA
