steps:
  - id: build-backend-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-f"
      - backend/Dockerfile
      - "-t"
      - gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA
      - .
    dir: .
images:
  - gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA