steps:
  - id: build-backend-image
    name: gcr.io/cloud-builders/docker
    # Always run from the checked-out workspace root so the Docker context has all manifests
    dir: /workspace
    args:
      - build
      - --file=backend/Dockerfile
      - --tag=gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA
      - .
images:
  - gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA
