steps:
  - id: build-backend-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=backend/Dockerfile
      - --tag=gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA
      - .
    # Build from the repo root so pnpm workspace files are included in the context.
    dir: .
images:
  - gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA
