steps:
  - id: build-backend-image
    name: gcr.io/cloud-builders/docker
    # Run from the repository root so the Docker context includes pnpm manifests and workspace files
    dir: /workspace/website
    args:
      - build
      - --file=backend/Dockerfile
      - --tag=gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA
      - .
images:
  - gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA
