steps:
  - id: build-backend-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=Dockerfile
      - --tag=gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA
      - ..
    # Run inside backend/ but send the repository root (..) as the Docker context so
    # pnpm workspace manifests are available to Dockerfile COPY commands.
    dir: backend
images:
  - gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA
