steps:
  - id: build-backend-image
    name: gcr.io/cloud-builders/docker
    # Build from the backend directory but send the monorepo root as context so lockfiles are available
    dir: backend
    args:
      - build
      - --file=./Dockerfile
      - --tag=gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA
      - ..
images:
  - gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA
