steps:
  - id: build-backend-image
    name: gcr.io/cloud-builders/docker
    dir: .
    # Use the monorepo root as the build context so the workspace lockfile is available to Docker
    args:
      - build
      - --file=backend/Dockerfile
      - --tag=gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA
      - .
images:
  - gcr.io/$PROJECT_ID/website-backend:$COMMIT_SHA
