// lib/seo/schema.ts

import { SITE_NAME, SITE_URL, SITE_DEFAULT_IMAGE } from "@/lib/constants";
import { getCanonicalUrl } from "./canonical"; // This helper is designed for RELATIVE paths

import type { WithContext, Thing, ImageObject } from "schema-dts";

const OG_IMAGE_DEFAULT_WIDTH = 1200;
const OG_IMAGE_DEFAULT_HEIGHT = 630;
const LOGO_DEFAULT_WIDTH = 600;
const LOGO_DEFAULT_HEIGHT = 60;

// Extend ImageObject to optionally include caption/alt for legacy compatibility
type ImageObjectWithCaption = ImageObject & { caption?: string; alt?: string };

// --- NEW HELPER FUNCTION TO AVOID DOUBLE DOMAINS IN SCHEMA.ORG URLS ---
// This function correctly canonicalizes a URL for Schema.org properties.
// It checks if the input URL is already absolute (starts with http/https or //).
// If it's absolute, it uses it as is. If it's relative, it uses getCanonicalUrl.
function getAbsoluteCanonicalUrlForSchema(inputUrl: string): string {
  // Check if the URL is already absolute
  if (inputUrl.startsWith("http://") || inputUrl.startsWith("https://") || inputUrl.startsWith("//")) {
    return inputUrl; // If already absolute, use it directly.
  }
  // If it's a relative path, use getCanonicalUrl to make it absolute from SITE_URL.
  return getCanonicalUrl(inputUrl);
}
// --- END NEW HELPER ---


/**
 * Generate Schema.org JSON-LD for any SEO context (WebPage, Article, etc.)
 * @template T Additional schema.org properties
 * @returns {WithContext<Thing>} JSON-LD schema object
 */
export function getSchema<T extends Record<string, any>>({
  type = "WebPage",
  path = "/",
  title,
  description,
  image = SITE_DEFAULT_IMAGE,
  logoUrl = `${SITE_URL}/logo.png`, // Default logoUrl is already an absolute URL.
  organizationName = SITE_NAME,
  organizationUrl = SITE_URL, // Default organizationUrl is already an absolute URL.
  authorName,
  datePublished,
  dateModified,
  additionalProperties = {},
}: {
  type?: string;
  path?: string;
  title: string;
  description: string;
  image?: string | Partial<ImageObjectWithCaption>;
  logoUrl?: string;
  organizationName?: string;
  organizationUrl?: string;
  authorName?: string;
  datePublished?: string;
  dateModified?: string;
  additionalProperties?: T;
}): WithContext<Thing> {
  // Canonical URL for the page itself (path is always relative here, so getCanonicalUrl is perfect)
  const url = getCanonicalUrl(path);

  // 1. Process the main image for schema
  let schemaImage: ImageObject;
  if (typeof image === "string") {
    schemaImage = {
      "@type": "ImageObject",
      url: getAbsoluteCanonicalUrlForSchema(image), // Use the new helper for image URL
      width: OG_IMAGE_DEFAULT_WIDTH,
      height: OG_IMAGE_DEFAULT_HEIGHT,
      caption: description,
    };
  } else if (typeof image === "object" && image !== null && "url" in image) {
    const img = image as Partial<ImageObjectWithCaption>;
    schemaImage = {
      "@type": "ImageObject",
      url: getAbsoluteCanonicalUrlForSchema(img.url!), // Use the new helper for image URL
      width: img.width || OG_IMAGE_DEFAULT_WIDTH,
      height: img.height || OG_IMAGE_DEFAULT_HEIGHT,
      caption: img.caption || img.alt || description,
    };
  } else {
    schemaImage = {
      "@type": "ImageObject",
      url: getAbsoluteCanonicalUrlForSchema(SITE_DEFAULT_IMAGE), // Use the new helper for default image URL
      width: OG_IMAGE_DEFAULT_WIDTH,
      height: OG_IMAGE_DEFAULT_HEIGHT,
      caption: description,
    };
  }

  // 2. Process the organization logo for schema
  const schemaLogo: ImageObject = {
    "@type": "ImageObject",
    url: getAbsoluteCanonicalUrlForSchema(logoUrl), // Use the new helper for logo URL
    width: LOGO_DEFAULT_WIDTH,
    height: LOGO_DEFAULT_HEIGHT,
    caption: `${organizationName} logo`,
  };

  // Base schema object (merge additionalProperties last for full override)
  const baseSchema: Thing = {
    "@context": "https://schema.org",
    "@type": type,
    name: title,
    description,
    url, // This 'url' is correctly generated by getCanonicalUrl(path)
    image: schemaImage,
    publisher: {
      "@type": "Organization",
      name: organizationName,
      url: getAbsoluteCanonicalUrlForSchema(organizationUrl), // Use the new helper for publisher URL
      logo: schemaLogo,
    },
    ...(type === "WebPage" && {
      mainEntityOfPage: {
        "@type": "WebPage",
        "@id": url, // This 'url' is correctly generated by getCanonicalUrl(path)
      },
    }),
    ...(type === "Article" && {
      mainEntityOfPage: {
        "@type": "WebPage",
        "@id": url, // This 'url' is correctly generated by getCanonicalUrl(path)
      },
      ...(authorName && {
        author: {
          "@type": "Person",
          name: authorName,
        },
      }),
      ...(datePublished && { datePublished }),
      ...(dateModified && { dateModified }),
      headline: title,
    }),
  };

  // Return as a schema.org WithContext object
  return {
    ...baseSchema,
    ...additionalProperties,
  } as WithContext<Thing>;
}
