#!/usr/bin/env ts-node

import crypto from "node:crypto";

interface Endpoint {
  method: string;
  path: string;
  description: string;
  body?: Record<string, unknown>;
  expectJson?: boolean;
  expectStatus?: number;
}

const DEFAULT_BACKEND_BASE =
  process.env.NEXT_PUBLIC_API_BASE_URL ||
  process.env.BACKEND_BASE_URL ||
  "http://localhost:4000";

type CliOptions = {
  backendBase: string;
};

function parseArgs(argv: string[]): CliOptions {
  let backendBase = DEFAULT_BACKEND_BASE;
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--backend-base") {
      backendBase = argv[i + 1] || backendBase;
      i += 1;
      continue;
    }
  }
  if (!arg.startsWith("--") && backendBase === DEFAULT_BACKEND_BASE) {
      backendBase = arg;
    }
    return { backendBase };
}

const { backendBase } = parseArgs(process.argv.slice(2));

const backendEndpoints: Endpoint[] = [
  { method: "GET", path: "/healthz", description: "Health check", expectJson: true },
  { method: "GET", path: "/posts", description: "List published blogs", expectJson: true },
  {
    method: "GET",
    path: "/posts/welcome-to-flavor-studios",
    description: "Fetch blog detail",
    expectJson: true,
  },
  { method: "GET", path: "/videos", description: "List published videos", expectJson: true },
  {
    method: "GET",
    path: "/videos/behind-the-scenes",
    description: "Fetch video detail",
    expectJson: true,
  },
  {
    method: "GET",
    path: "/categories?type=blog",
    description: "Blog categories",
    expectJson: true,
  },
  {
    method: "GET",
    path: "/comments?postId=fallback-welcome-to-flavor-studios&postType=blog",
    description: "Comments listing",
    expectJson: true,
  },
  {
    method: "POST",
    path: "/comments",
    description: "Submit comment",
    expectJson: true,
    expectStatus: 201,
    body: {
      author: "Smoke Test",
      content: "Synthetic comment from scripts/smoke-api.ts",
      postId: "fallback-welcome-to-flavor-studios",
      postType: "blog",
    },
  },
  {
    method: "POST",
    path: "/contact",
    description: "Submit contact form",
    expectJson: true,
    expectStatus: 202,
    body: {
      firstName: "Smoke",
      lastName: "Test",
      email: "smoke@example.com",
      subject: "API Smoke Test",
      message: "This is a synthetic request generated by scripts/smoke-api.ts.",
    },
  },  
];

function prettyDuration(ms: number): string {
  return `${ms.toFixed(0)}ms`;
}

async function run() {
  console.log(`\nAPI smoke test against backend ${backendBase}`);
  console.log("--------------------------------------");

  for (const endpoint of backendEndpoints) {
    const url = new URL(endpoint.path, backendBase);
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 15000);
    const requestId = crypto.randomUUID();
    const start = performance.now();

    try {
      const headers: Record<string, string> = {
        "X-Request-ID": requestId,
      };
      if (endpoint.body) {
        headers["Content-Type"] = "application/json";
      }

      const res = await fetch(url, {
        method: endpoint.method,
        cache: "no-store",
        headers,
        body: endpoint.body ? JSON.stringify(endpoint.body) : undefined,
        signal: controller.signal,
      });
      const duration = performance.now() - start;
      let jsonValid = false;
      let bodySnippet = "";

      if (endpoint.expectJson) {
        try {
          const data = await res.clone().json();
          jsonValid = true;
          bodySnippet = JSON.stringify(data).slice(0, 120);
        } catch (error) {
          jsonValid = false;
          bodySnippet = `Invalid JSON (${(error as Error).message})`;
        }
      } else {
        bodySnippet = await res.clone().text().then((text) => text.slice(0, 120));
      }

      const statusMatch = res.status === (endpoint.expectStatus ?? 200);
      const statusLine = `${endpoint.method.padEnd(6)} ${endpoint.path.padEnd(40)} ${res.status
        .toString()
        .padEnd(4)} ${prettyDuration(duration).padStart(6)} ${jsonValid ? "JSON" : "TEXT"}`;
      console.log(`${statusLine} – ${endpoint.description}`);
      if (!statusMatch || (endpoint.expectJson && !jsonValid)) {
        console.log(`  ↳ Response snippet: ${bodySnippet}`);
      }
      if (!statusMatch) {
        throw new Error(`Unexpected status for ${endpoint.path}`);
      }
    } catch (error) {
      clearTimeout(timeout);
      const prefix = `${endpoint.method.padEnd(6)} ${endpoint.path.padEnd(40)}`;
      if (error instanceof Error && error.name === "AbortError") {
        console.error(`${prefix} FAIL --   Timed out after 15s (${requestId})`);
      } else {
        console.error(`${prefix} FAIL --   ${(error as Error).message}`);
      }
      process.exit(1);
    } finally {
      clearTimeout(timeout);
    }
  }
}

run().catch((error) => {
  console.error("Smoke test failed", error);
  process.exitCode = 1;
});